server:
  port: 7003
spring:
  profiles:
    active: dev
  application:
    name: etocrm-sdk-server1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://10.10.30.44:8123/eto?socket_timeout=300000
      username: sdk
      password: qMBdmBAE
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
    db3:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      jdbcurl: jdbc:clickhouse://10.10.30.45:8123/eto
      username: sdk
      password: qMBdmBAE
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcurl: jdbc:mysql://10.10.30.44:3306/sdk
      username: dev_root
      password: dt6l^thgogTy
      maxLifetime: 60000
      maximumpoolsize: 20
      minimumIdle: 10
      autoCommit: true
      idleTimeout: 60000
      poolName: DatebookHikariCP
      connectionTimeout: 60000
      connectiontestQuery: select 1
      validationTimeout: 3000
mybatis:
  type-aliases-package: com.etocrm.sdk.entity
  #mapper-locations: classpath:/mapper/*.xml,classpath:/mysqlmapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com.etocrm.sdk.dao : error



#mybatis-plus:
#  typeAliasesPackage: com.etocrm.sdk.entity
#  mapperLocations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  production: false
  enable: true